# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x12\x1b\x64\x65v.desu.rpcservice.service\"i\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nclientName\x18\x02 \x01(\t\x12\x10\n\x08senderId\x18\x03 \x01(\x03\x12\x14\n\nsenderName\x18\x04 \x01(\tH\x00\x42\x11\n\x0fsenderNameOneOf2h\n\tBotMutual\x12[\n\x07\x43onnect\x12$.dev.desu.rpcservice.service.Message\x1a$.dev.desu.rpcservice.service.Message\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=42
  _globals['_MESSAGE']._serialized_end=147
  _globals['_BOTMUTUAL']._serialized_start=149
  _globals['_BOTMUTUAL']._serialized_end=253
# @@protoc_insertion_point(module_scope)
